package command

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// shellCommand prints or installs bash completion for this CLI: `show` prints
// the script so it can be reviewed or sourced by hand, `install` copies it to
// where bash's own completion machinery loads it from automatically.
var shellCommand = Command{
	usage:          "shell <show|install>",
	requiresClient: false,
	run: func(_ *GerritClient, args []string) error {
		if len(args) != 1 {
			return fmt.Errorf("ERROR: shell requires exactly one subcommand: show, install")
		}

		program := programName(os.Args)

		switch action := args[0]; action {
		case "show":
			return shellShow(program)
		case "install":
			return shellInstall(program)
		default:
			return fmt.Errorf("ERROR: unknown shell subcommand '%s'. Use: show, install", action)
		}
	},
}

// currentShell detects which shell to integrate with through $SHELL, which is
// set by the login shell itself rather than guessed from the parent process.
// Only bash is supported - the script below is written for bash's own
// completion machinery, and a shell that cannot load it is told so rather
// than handed a file it will never source.
func currentShell() (string, error) {
	value := strings.TrimSpace(os.Getenv("SHELL"))
	if value == "" {
		return "", fmt.Errorf("ERROR: SHELL is not set, cannot detect the current shell")
	}

	name := filepath.Base(value)
	// On Windows, msys reports the native shell binary with its extension
	// (bash.exe) rather than the plain name a Unix $SHELL carries.
	name = strings.TrimSuffix(name, ".exe")

	if name != "bash" {
		return "", fmt.Errorf("ERROR: completion is not supported for the current shell: %s\nsupported shells: bash", name)
	}

	return name, nil
}

// shellShow prints the completion script for the current shell, so it can be
// reviewed before it is trusted, or sourced directly: . <(gerrit-cli shell show).
func shellShow(program string) error {
	if _, err := currentShell(); err != nil {
		return err
	}

	fmt.Print(bashCompletionScript(program))
	return nil
}

// isGitBash reports whether the running shell is Git for Windows' bundled
// MSYS bash rather than a real bash-completion-equipped install. Git for
// Windows sets $MSYSTEM (to MINGW64, MINGW32 or MSYS) in every shell it
// starts; nothing else sets it, so its presence alone is enough to detect it.
func isGitBash() bool {
	return os.Getenv("MSYSTEM") != ""
}

// bashCompletionTarget is where a new shell will pick the completion script
// up from, which depends on how bash itself was set up rather than anything
// this CLI controls:
//   - Git for Windows ships MSYS bash with no bash-completion package at all;
//     its own /etc/profile.d/git-prompt.sh instead auto-sources
//     ${HOME}/bash_completion.d/<program>.bash, so that is the only path a
//     Git Bash install will ever actually read.
//   - Everywhere else, ${HOME}/.local/share/bash-completion/completions/<program>
//     is the bash-completion package's own dynamic-loading convention.
func bashCompletionTarget(program string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("ERROR: cannot find the home directory: %v", err)
	}

	if isGitBash() {
		return filepath.Join(home, "bash_completion.d", program+".bash"), nil
	}

	return filepath.Join(home, ".local", "share", "bash-completion", "completions", program), nil
}

// shellInstall copies the completion script to bash's completion directory,
// replacing whatever is there - including a symlink from an earlier install,
// which is removed rather than written through - so the next shell started
// picks it up without the user having to source anything by hand.
func shellInstall(program string) error {
	if _, err := currentShell(); err != nil {
		return err
	}

	target, err := bashCompletionTarget(program)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("ERROR: cannot create %s: %v", filepath.Dir(target), err)
	}

	_ = os.Remove(target)

	if err := os.WriteFile(target, []byte(bashCompletionScript(program)), 0o644); err != nil {
		return fmt.Errorf("ERROR: cannot write %s: %v", target, err)
	}

	fmt.Printf("shell completion is installed to %s\n", target)
	fmt.Printf("start a new shell or run: . \"%s\"\n", target)
	return nil
}

// bashCompletionScript is the completion script itself, parameterized by the
// program name so a renamed or `go build`-produced binary still completes
// under whatever name it is actually invoked as. It knows the command tree
// and the reserved flags directly, both fixed in this CLI's own source.
func bashCompletionScript(program string) string {
	return fmt.Sprintf(bashCompletionTemplate, program)
}

const bashCompletionTemplate = `# bash completion for %[1]s
# generated by: %[1]s shell show

_gerrit_cli_completion() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Walk the already-typed words, splitting them into the positional path
    # (the command and its subcommands) and the reserved flags: --name=value
    # carries its own value, and every other --flag consumes the word after it.
    local -a path
    local i=1
    while [ "$i" -lt "$COMP_CWORD" ]; do
        local word="${COMP_WORDS[$i]}"
        case "$word" in
            --*=*)
                i=$((i + 1))
                ;;
            --*)
                i=$((i + 2))
                ;;
            *)
                path+=("$word")
                i=$((i + 1))
                ;;
        esac
    done

    local p0="${path[0]:-}"
    local p1="${path[1]:-}"

    # A value is being completed for the flag just typed, not a flag name or a
    # positional word. --change-id and --review-url take arbitrary values, so
    # there is nothing to offer.
    if [[ "$prev" == --* ]]; then
        return 0
    fi

    # A flag name is being completed: offer the ones this command reads.
    if [[ "$cur" == --* ]]; then
        local flags="--help"
        case "$p0" in
            get-change | get-files | get-commit | get-diff | get-messages | get-patch | \
            get-moab-numbers | get-publish-version | is-verified | post-comment)
                flags="$flags --change-id --review-url"
                ;;
        esac
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
    fi

    # Otherwise a command or subcommand word is being completed, one level
    # below however far the positional path already reaches.
    local candidates=""
    case "${#path[@]}" in
        0)
            candidates="keychain get-change get-files get-commit get-diff get-messages get-patch get-moab-numbers get-publish-version is-verified post-comment resolve-change-number resolve-change-id shell"
            ;;
        1)
            case "$p0" in
                keychain) candidates="set remove clear status" ;;
                shell) candidates="show install" ;;
            esac
            ;;
        2)
            case "$p0 $p1" in
                "keychain set" | "keychain remove") candidates="username password" ;;
            esac
            ;;
    esac

    COMPREPLY=( $(compgen -W "$candidates" -- "$cur") )
    return 0
}

complete -o default -F _gerrit_cli_completion %[1]s
`
